In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv("loan.csv")

In [3]:
df.head()

Gender  Age  Salary  Default
0      M   24   21730        0
1      M   40   22730        0
2      F   31   45730        0
3      F   32   59730        0
4      M   24   78730        0

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [5]:
num_vars= ['Age', 'Salary']
cat_vars= ['Gender']

In [6]:
abc= SimpleImputer(strategy="median")
efg= SimpleImputer(strategy="most_frequent")
one= OneHotEncoder(sparse=False)
sc=StandardScaler()

In [7]:
numerical_transformer = Pipeline(steps= [
    ('sdadad', abc),
    ('saddad', sc)
])

In [8]:
cat_transformer = Pipeline(steps= [
    ('sdadad', efg),
    ('saddad', one)
])

In [9]:
preprocessor= ColumnTransformer(transformers=[
    ('efwefwe', numerical_transformer, num_vars),
    ('saddwa', cat_transformer, cat_vars)
])

In [10]:
preprocessor.fit(df)

ColumnTransformer(n_jobs=None, remainder='drop', sparse_threshold=0.3,
         transformer_weights=None,
         transformers=[('efwefwe', Pipeline(memory=None,
     steps=[('sdadad', SimpleImputer(copy=True, fill_value=None, missing_values=nan,
       strategy='median', verbose=0)), ('saddad', StandardScaler(copy=True, with_mean=True, with_std=True))]), ['Age', 'Salary']), ('saddwa', Pipeline(memory=None,
   ...class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=False))]), ['Gender'])])

In [12]:
X= preprocessor.transform(df)
y= df.Default

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=123)

In [14]:
log_lr = LogisticRegression()

In [15]:
log_lr.fit(X_train, y_train)

C:\Users\adity\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [16]:
y_pred= log_lr.predict(X_test)

In [18]:
y_pred   #actual predicted classes

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1], dtype=int64)

In [21]:
y_pred_prob= log_lr.predict_proba(X_test)

In [22]:
y_pred_prob

array([[0.42428437, 0.57571563],
       [0.56782284, 0.43217716],
       [0.6898847 , 0.3101153 ],
       [0.98536728, 0.01463272],
       [0.76856591, 0.23143409],
       [0.84299603, 0.15700397],
       [0.97434435, 0.02565565],
       [0.0411141 , 0.9588859 ],
       [0.43506124, 0.56493876],
       [0.76419153, 0.23580847],
       [0.93758322, 0.06241678],
       [0.55680045, 0.44319955],
       [0.23763545, 0.76236455],
       [0.97985185, 0.02014815],
       [0.91420479, 0.08579521],
       [0.10024843, 0.89975157],
       [0.96282607, 0.03717393],
       [0.91881496, 0.08118504],
       [0.93427967, 0.06572033],
       [0.85859332, 0.14140668],
       [0.95380602, 0.04619398],
       [0.81719603, 0.18280397],
       [0.99424205, 0.00575795],
       [0.87172558, 0.12827442],
       [0.91503172, 0.08496828],
       [0.60201138, 0.39798862],
       [0.98254168, 0.01745832],
       [0.01318658, 0.98681342],
       [0.77539899, 0.22460101],
       [0.51883085, 0.48116915],
       [0.

In [23]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_test, y_pred)

0.8375

In [26]:
from sklearn.metrics import confusion_matrix

In [28]:
confusion_matrix(y_test, y_pred, labels=[0,1])

array([[47,  3],
       [10, 20]], dtype=int64)

# knn classifier

In [29]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
knn = KNeighborsClassifier(n_neighbors=5)

In [31]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [32]:
y_pred_knn= knn.predict(X_test)

In [33]:
accuracy_score(y_test, y_pred_knn)

0.875

# Decision Tree


In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
dc= DecisionTreeClassifier()

In [36]:
dc.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [37]:
y_pred_dc= dc.predict(X_test)

In [38]:
accuracy_score(y_test, y_pred_dc)

0.85

# Bagging

In [42]:
from sklearn.ensemble import BaggingClassifier

In [43]:
bag= BaggingClassifier(n_estimators=100, max_samples=0.3)

In [44]:
bag.fit(X_train, y_train)

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=0.3,
         n_estimators=100, n_jobs=None, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

In [45]:
y_pred_bag= bag.predict(X_test)

In [46]:
accuracy_score(y_test, y_pred_bag)

0.875

# Random Forest

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [52]:
bag = RandomForestClassifier(n_estimators=1000)           ##maxfeatures

In [53]:
bag.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [54]:
y_pred_bag= bag.predict(X_test)

In [55]:
accuracy_score(y_test, y_pred_bag)

0.875

# Boosting

In [56]:
from sklearn.ensemble import GradientBoostingClassifier

In [57]:
gbm= GradientBoostingClassifier(n_estimators=100)

In [58]:
gbm.fit(X_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [59]:
y_pred_gbm = gbm.predict(X_test)

In [60]:
accuracy_score(y_test, y_pred_gbm)

0.8625