In [1]:
import numpy as np
import pandas as pd
df= pd.read_csv("available_data.csv")

In [5]:
df

emp_id  gender   age    salary  has_car
0       1    Male  25.0   86177.0        1
1       2    Male  27.0   67961.0        0
2       3  Female   NaN   88344.0        0
3       4    Male  30.0   86222.0        1
4       5  Female  24.0  105669.0        0
5       6  Female  36.0       NaN        1
6       7     NaN  48.0   68091.0        0
7       8  Female  27.0   65480.0        1
8       9  Female  25.0   79193.0        1
9      10    Male  31.0  104414.0        0

In [13]:
## some missing values can be seen
## i/p cols = gender, age, salary
## o/p col = has_car -- whether the person has a car or not
#
## categorical values
## range of age- 20 to 60, range of salary - 50k to 100k --> need to represent on the same scale (data scaling)

In [18]:
##pip install sklearn -- upgrade ##update in new terminal and then restart notebook


The following command must be run outside of the IPython shell:

    $ pip install sklearn -- upgrade ##update in new terminal and then restart notebook

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/


In [66]:
X = df.iloc[ :,1:4].values  ## just want values

In [67]:
X

array([['Male', 25.0, 86177.0],
       ['Male', 27.0, 67961.0],
       ['Female', nan, 88344.0],
       ['Male', 30.0, 86222.0],
       ['Female', 24.0, 105669.0],
       ['Female', 36.0, nan],
       [nan, 48.0, 68091.0],
       ['Female', 27.0, 65480.0],
       ['Female', 25.0, 79193.0],
       ['Male', 31.0, 104414.0]], dtype=object)

In [68]:
y = df.iloc[ : , -1].values

In [69]:
from sklearn.impute import SimpleImputer

In [70]:
numerical_imputer = SimpleImputer(missing_values=np.NaN, ##created an object of simple imputer class
                                 strategy = "median")  ##function for replacing row with empty value to median

In [71]:
categorical_imputer = SimpleImputer(missing_values=np.NaN,
                                   strategy ="most_frequent") ##function for categorical columns

In [72]:
numerical_imputer.fit(X[ :,1:3])

SimpleImputer(copy=True, fill_value=None, missing_values=nan,
       strategy='median', verbose=0)

In [73]:
categorical_imputer.fit(X[ : , 0:1])  ##writing just 0 will give you an error since that will be an array and we need matrixorlist? so use 0:1 or [0]

SimpleImputer(copy=True, fill_value=None, missing_values=nan,
       strategy='most_frequent', verbose=0)

In [74]:
X[ : ,1:3] = numerical_imputer.transform(X[ : ,1:3])

In [75]:
X[ : , [0]] = categorical_imputer.transform(X[ :, [0]])

In [76]:
from sklearn.preprocessing import OneHotEncoder

In [77]:
from sklearn.compose import ColumnTransformer

In [78]:
gender_encoder = OneHotEncoder(sparse=False)                ##dont need a sparse matrix, by default it’s true

In [79]:
##clm = ColumnTransformer()  ##object for column transformer, it needs a list of different models(like gender_encoder)

In [80]:
clm= ColumnTransformer(transformers = [
    ('categorical', gender_encoder, [0]) 
], remainder = 'passthrough' )                         ## name of new column, what to use on it, column number – still making a blueprint, passthrough – pass it as it is or else it will affect the other numerical columns


In [81]:
clm.fit(X)           ##model trained

ColumnTransformer(n_jobs=None, remainder='passthrough', sparse_threshold=0.3,
         transformer_weights=None,
         transformers=[('categorical', OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=False), [0])])

In [82]:
X= clm.transform(X)

In [83]:
X

array([[0.0, 1.0, 25.0, 86177.0],
       [0.0, 1.0, 27.0, 67961.0],
       [1.0, 0.0, 27.0, 88344.0],
       [0.0, 1.0, 30.0, 86222.0],
       [1.0, 0.0, 24.0, 105669.0],
       [1.0, 0.0, 36.0, 86177.0],
       [1.0, 0.0, 48.0, 68091.0],
       [1.0, 0.0, 27.0, 65480.0],
       [1.0, 0.0, 25.0, 79193.0],
       [0.0, 1.0, 31.0, 104414.0]], dtype=object)

In [84]:
from sklearn.preprocessing import StandardScaler

In [85]:
sc = StandardScaler()

In [86]:
sc.fit(X)

C:\Users\adity\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [87]:
X = sc.transform(X)

C:\Users\adity\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [88]:
X

array([[-1.22474487,  1.22474487, -0.72624112,  0.17942338],
       [-1.22474487,  1.22474487, -0.43574467, -1.18002106],
       [ 0.81649658, -0.81649658, -0.43574467,  0.34114473],
       [-1.22474487,  1.22474487,  0.        ,  0.18278169],
       [ 0.81649658, -0.81649658, -0.87148934,  1.63409461],
       [ 0.81649658, -0.81649658,  0.87148934,  0.17942338],
       [ 0.81649658, -0.81649658,  2.61446802, -1.17031927],
       [ 0.81649658, -0.81649658, -0.43574467, -1.36517596],
       [ 0.81649658, -0.81649658, -0.72624112, -0.34178654],
       [-1.22474487,  1.22474487,  0.14524822,  1.54043504]])

In [89]:
y

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 0], dtype=int64)

In [90]:
from sklearn.model_selection import train_test_split

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)   ##can use random_state for setting seed

In [92]:
X_train

array([[-1.22474487,  1.22474487,  0.14524822,  1.54043504],
       [-1.22474487,  1.22474487, -0.43574467, -1.18002106],
       [ 0.81649658, -0.81649658, -0.87148934,  1.63409461],
       [ 0.81649658, -0.81649658, -0.43574467, -1.36517596],
       [-1.22474487,  1.22474487,  0.        ,  0.18278169],
       [ 0.81649658, -0.81649658, -0.72624112, -0.34178654],
       [-1.22474487,  1.22474487, -0.72624112,  0.17942338],
       [ 0.81649658, -0.81649658, -0.43574467,  0.34114473]])

In [93]:
X_test

array([[ 0.81649658, -0.81649658,  0.87148934,  0.17942338],
       [ 0.81649658, -0.81649658,  2.61446802, -1.17031927]])

In [94]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 0], dtype=int64)

In [95]:
y_test

array([1, 0], dtype=int64)

# Data prep done, starting to implement models